name: Keep Services Alive

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ml, backend]

    steps:
      - name: Ping ${{ matrix.service }} service
        run: |
          if [[ "${{ matrix.service }}" == "ml" ]]; then
            echo "Pinging Hugging Face API..."
            curl --fail --silent --show-error -H "X-Heartbeat: true" "${{ secrets.ML_API_URL }}" || echo "Ping failed but continuing."
          elif [[ "${{ matrix.service }}" == "backend" ]]; then
            echo "Pinging Backend API..."
            curl --fail --silent --show-error -H "X-Heartbeat: true" "${{ secrets.FRONTEND_BACKEND_API_URL }}/api/status" || echo "Ping failed but continuing."
          else
            echo "Unknown service."
          fi
